#include "nsISupports.idl"
#include "nsIEveItem.idl"
#include "nsIEveSkill.idl"
interface nsIDOMElement;
interface nsIEveServerStatus;

[scriptable, uuid(6f7ee12b-12b3-4101-a4c9-ecdc97c51421)]
interface nsIEveApiService : nsISupports {
    readonly attribute string error;
    nsIEveServerStatus getServerStatus();
    nsIDOMElement getCharacterList(in string id, in string key);
    void getCharacterAssets(in string id, in string key, in string charID,
            out unsigned long count,
            [array, size_is(count), retval] out nsIEveItem retv);
    void getCorporationAssets(in string id, in string key, in string charID,
            out unsigned long count,
            [array, size_is(count), retval] out nsIEveItem retv);
    void getCharacterSkills(in string id, in string key, in string charID,
            out unsigned long count, [array, size_is(count), retval] out nsIEveSkill retv);
};

[scriptable, uuid(b0274794-98da-45fd-8cf1-361cac351395)]
interface nsIEveServerStatus : nsISupports {
    boolean isOnline();
    readonly attribute long onlinePlayers;
};

