#include "nsISupports.idl"

[scriptable, uuid(965384f6-8eb6-4173-a34b-4f6ce71a79bc)]
interface nsIEveItem : nsISupports {
    readonly attribute long id;
    readonly attribute long location;
    readonly attribute long container;
    readonly attribute long type;
    readonly attribute long quantity;
    readonly attribute short flag;
    readonly attribute boolean singleton;
    string toString();
    string locationString();
    string containerString();
};

[scriptable, uuid(711dae78-b38a-40a7-93d5-acbc3bc9d51a)]
interface nsIEveItemBuilder : nsISupports {
    void createItem(in long id, in long location, in long container,
            in long type, in long quantity, in short flag,
            in boolean singleton, [retval] out nsIEveItem item);
};

