#include "nsISupports.idl"
#include "EveConstants.idl"

[scriptable, uuid(c6159d08-5512-43f5-8e54-722ccce3ced5)]
interface nsIEveItemCategory : nsISupports {
    readonly attribute long id;
    readonly attribute string name;
};

[scriptable, uuid(7f894b5e-f91d-4608-98c0-db99c2c0e9e0)]
interface nsIEveItemGroup : nsISupports {
    readonly attribute nsEveItemGroupIDValue id;
    readonly attribute string name;
    readonly attribute nsIEveItemCategory category;
};

[scriptable, uuid(b0da4573-23a6-4c6d-9c67-b09ee6fb5f9e)]
interface nsIEveItemType : nsISupports {
    readonly attribute nsEveItemTypeIDValue id;
    readonly attribute string name;
    readonly attribute nsIEveItemGroup group;
};

[scriptable, uuid(965384f6-8eb6-4173-a34b-4f6ce71a79bc)]
interface nsIEveItem : nsISupports {
    readonly attribute long id;
    readonly attribute long location;
    readonly attribute nsIEveItem container;
    readonly attribute nsIEveItemType type;
    readonly attribute long quantity;
    readonly attribute short flag;
    readonly attribute boolean singleton;
    string toString();
    string locationString();
    string containerString();
    boolean isContainer();
    void getItemsInside(out unsigned long count,
            [array, size_is(count), retval] out nsIEveItem retv);
    void addItem(in nsIEveItem item);
    void removeItem(in nsIEveItem item);
};

[scriptable, uuid(711dae78-b38a-40a7-93d5-acbc3bc9d51a)]
interface nsIEveItemBuilder : nsISupports {
    void createItem(in long id, in long location, in nsIEveItem container,
            in long typeID, in long quantity, in short flag,
            in boolean singleton, [retval] out nsIEveItem item);
    void getItemType(in long id, [retval] out nsIEveItemType type);
    void getItemGroup(in long id, [retval] out nsIEveItemGroup type);
    void getItemCategory(in long id, [retval] out nsIEveItemCategory type);
};

