#include "nsISupports.idl"
#include "EveConstants.idl"

[scriptable, uuid(557932e0-d69e-4d4f-a322-f93d1d4b06ac)]
interface nsIEveLocation : nsISupports {
    readonly attribute nsEveLocationType type; 
    readonly attribute long id;
    readonly attribute string name;    
};
